# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
jaccard_coeff <- function(idx) {
    .Call('_briDiscovr_jaccard_coeff', PACKAGE = 'briDiscovr', idx)
}

